development:
  adapter: mysql
  encoding: utf8
  database: crawlr_development
  username: pau
  password: 
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: crawlr_test
  username: pau
  password: 
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  database: crawlr_production
  username: pau
  password: 
  socket: /Applications/MAMP/tmp/mysql/mysql.sock